# Generated by Django 4.0.2 on 2022-02-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
