# Generated by Django 4.0.2 on 2022-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_form_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='issue',
        ),
        migrations.AddField(
            model_name='form',
            name='enquiry',
            field=models.CharField(default='', max_length=255),
        ),
    ]
