# Generated by Django 4.0.2 on 2022-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_store_id_alter_store_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_id',
        ),
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
