# Generated by Django 4.0.2 on 2022-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_nos', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=255)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('issue', models.CharField(default='', max_length=255)),
                ('ticket_status', models.CharField(default='Active', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
