# Generated by Django 4.0.2 on 2022-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ticket_delete_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=255)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('vouch', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
